[package]
name = "dht"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
distributed-topic-tracker = { git = "https://github.com/rustonbsd/distributed-topic-tracker", version = "0.2.5" }
ed25519-dalek = "3.0.0-pre.1"
iroh = "0.95"
iroh-gossip = "0.95"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
tracing-subscriber = "0.3.20"
