[package]
name = "id"
version = "0.1.0"
edition = "2024"
[dependencies]
anyhow = "1"
distributed-topic-tracker = { git = "https://github.com/rustonbsd/distributed-topic-tracker" }
ed25519-dalek = { version = "3.0.0-pre.1", features = ["rand_core"] }
iroh = "0.95"
iroh-base = "0.95"
iroh-blobs = "0.97"
iroh-gossip = { version = "0.95", features = ["net"] }
postcard = { version = "1", features = ["alloc"] }
rand = "0.9"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
